repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.0
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports, --explicit-package-bases]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.7
    hooks:
    -   id: ruff
        args: [--ignore=E501]
