services:
  pg:
    image: postgres:18
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${DB__NAME} -U $${DB__USER}" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped


  redis:
    image: redis
    volumes:
      - redisdata:/data


  deepface:
    build:
      dockerfile: Dockerfile
      context: ./api_deepface
    expose:
        - ${API_DEEPFACE_PORT}


  kandinsky:
    build:
      dockerfile: Dockerfile
      context: ./api_kandinsky
    expose:
        - ${API_KANDINSKY_PORT}


  app:
    build:
      dockerfile: app/Dockerfile
      context: .
    command:
      - gunicorn
      - app.main:app
      - --timeout
      - "2000"
      - --workers
      - "2"
      - --worker-class
      - uvicorn.workers.UvicornWorker
      - --bind
      - 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started
      pg:
        condition: service_healthy
#      deepface:
#        condition: service_started
#      kandinsky:
#        condition: service_started

volumes:
  postgresdata:
  redisdata:
